git clone https://github.com/cyweb/hammer
git clone https://github.com/theshadowbrokerss/Blue-Thunder-IP-Locator-
curl -LO https://raw.githubusercontent.com/Hax4us/Metasploit_termux/master/metasploit.sh
git clone https://github.com/xHak9x/fbi
git clone https://github.com/laramies/metagoofil
git clone https://github.com/laramies/theHarvester
git clone https://github.com/ilektrojohn/creepy/
git clone https://github.com/martinvigo/email2phonenumber
git clone https://github.com/1N3/Goohak
git clone https://github.com/jofpin/trape
git clone https://github.com/evilsocket/xray
git clone https://github.com/s0md3v/Photon
git clone https://github.com/twintproject/twint
git clone https://github.com/smicallef/spiderfoot
git clone https://github.com/1N3/Sn1per
git clone https://github.com/vaguileradiaz/tinfoleak
git clone https://github.com/maldevel/IPGeoLocation
git clone https://github.com/s0md3v/Breacher
git clone https://github.com/methos2016/recon-ng
git clone https://github.com/khast3x/h8mail